apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: knote-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: hederdevops.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: knote
            port:
              number: 80
