# aws-load-balancer-controller/values.yaml

image:
  repository: amazon/aws-alb-ingress-controller
  tag: latest

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: alb-ingress-controller

rbac:
  create: true

extraArgs: {}

tls:
  acm:
    enabled: true
    secretName: knote-tls-secret
    certificateARN: arn:aws:acm:your-region:your-account-id:certificate/your-acm-certificate-id

