apiVersion: v1
kind: Service
metadata:
  namespace: knote-app
  name: knote
  annotations:
    external-dns.alpha.kubernetes.io/hostname: www.hederdevops.com

spec:
  selector:
    app: knote
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP #LoadBalancer #NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: knote-app
  name: knote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knote
  template:
    metadata:
      labels:
        app: knote
    spec:
      containers:
        - name: knote
          image: heder24/my-app:knote
          ports:
            - containerPort: 3000
      # imagePullSecrets:
      #   - name: regcred

          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
            - name: MINIO_ACCESS_KEY
              value: mykey
            - name: MINIO_SECRET_KEY
              value: mysecret
            - name: MINIO_HOST
              value: minio
          imagePullPolicy: Always
