name: Deploy AWS Load Balancer Controller
# env:
#   DOCKER_USER: ${{secrets.DOCKER_HUB_USER}}
#   DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_TOKEN}}
#   DOCKER_REPOSITORY: my-app
#   NODE_IMAGE_TAG: knote

on:
  push:
    branches: [ main]

permissions:
  actions: read
  security-events: write
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Set K8s context
      uses: ossrs/k8s-set-context-action@v1
      with:
        kubeconfig: '${{ secrets.KUBECONFIG }}'

    - name:  update kubeconfig
      run : |
         aws eks update-kubeconfig --region us-east-2 --name prod

    # - name: Set up Helm
    #   uses: azure/setup-helm@v3
    #   with:
    #     version: 'latest'
  
    - name: Install eksctl
      run: |
        ARCH=amd64
        PLATFORM=$(uname -s)_$ARCH

        curl -sLO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz"

        # (Optional) Verify checksum
        curl -sL "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_checksums.txt" | grep $PLATFORM | sha256sum --check

        tar -xzf eksctl_$PLATFORM.tar.gz -C /tmp && rm eksctl_$PLATFORM.tar.gz

        sudo mv /tmp/eksctl /usr/local/bin
      shell: bash

    - name: Verify eksctl installation
      run: eksctl version

    - name: Create IAM OIDC provider
      run: |
        eksctl utils associate-iam-oidc-provider \
        --region=us-east-2 \
        --cluster=prod \
        --approve

    - name: Download IAM policy for the AWS Load Balancer Controller
      run: |
        curl -o iam-policy.json https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/main/docs/install/iam_policy.json


    # - name: Create an IAM policy called AWSLoadBalancerControllerIAMPolicy
    #   run: |
    #     aws iam create-policy \
    #     --policy-name AWSLoadBalancerControllerIAMPolicy \
    #     --policy-document file://iam-policy.json

    - name: Create a IAM role and ServiceAccount for the Load Balancer controller
      run: |
        eksctl create iamserviceaccount \
          --cluster=prod \
          --namespace=kube-system \
          --name=aws-load-balancer-controller \
          --role-name=AmazonEKSLoadBalancerControllerRole \
          --attach-policy-arn=arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:policy/AWSLoadBalancerControllerIAMPolicy \
          --override-existing-serviceaccounts \
          --approve

    - name: Install Helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh

    - name: Verify Helm installation
      run: helm version

    - name: Add Helm repository
      run: |
        helm repo add eks https://aws.github.io/eks-charts

    - name: Update Helm repositories
      run: |
        helm repo update

    - name: Install CRDS
      run: |
        kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller/crds?ref=master"
   
    # - name: Fix deadline issue
    #   run: |
    #     kubectl patch deployment/aws-load-balancer-controller -p '{"spec":{"progressDeadlineSeconds":600}}' -n kube-system
    - name: Deploy AWS Load Balancer Controller
      run: |
        helm upgrade -i aws-load-balancer-controller eks/aws-load-balancer-controller \
          --set clusterName=prod \
          --set serviceAccount.create=false \
          --set serviceAccount.name=aws-load-balancer-controller \
          -n kube-system
          --kubectl patch deployment/aws-load-balancer-controller -p '{"spec":{"progressDeadlineSeconds":600}}' -n kube-system
  
    - name: Verify deployment
      run: |
        kubectl get deployment -n kube-system aws-load-balancer-controller

    # - name: Deploy NGINX Ingress Controller
    #   run: |
    #     kubectl create namespace ingress-nginx
    #     helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
    #     helm repo update
    #     helm install ingress-nginx ingress-nginx/ingress-nginx --create-namespace --namespace kube-system --set controller.service.type=LoadBalancer --set controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-type"="nlb"
    # - name: Verify deployment
    #   run: |
    #      kubectl get deployment -n ingress-nginx-controller

  
    - name: Deploy load balancer to EKS
      run: | 
        kubectl apply -f ingress.yml

        



