name: Deploy AWS Load Balancer Controller
# env:
#   DOCKER_USER: ${{secrets.DOCKER_HUB_USER}}
#   DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_TOKEN}}
#   DOCKER_REPOSITORY: my-app
#   NODE_IMAGE_TAG: knote

on:
  push:
    branches: [ main]

permissions:
  actions: read
  security-events: write
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Set K8s context
      uses: ossrs/k8s-set-context-action@v1
      with:
        kubeconfig: '${{ secrets.KUBECONFIG }}'

    - name:  update kubeconfig
      run : |
         aws eks update-kubeconfig --region us-east-2 --name prod

    - name: Install eksctl
      run: |
        sudo curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin

    - name: Verify eksctl installation
      run: eksctl version

    - name: Install Helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh

    - name: Verify Helm installation
      run: helm version

    - name: Create Docker Registry Secret
      run: |
        kubectl create secret docker-registry regcred \
        --docker-server=https://index.docker.io/v1/ \
        --docker-username=${{secrets.DOCKER_HUB_USER}} \
        --docker-password=${{secrets.DOCKER_HUB_TOKEN}} \
        --docker-email=hederredon@gmail.com

  
    # - name: Deploy manifest files to EKS
    #   run: | 
        
    #     # # kubectl apply -f ingresss.yml
    #     # kubectl apply -f knote.yml
    #     # kubectl apply -f minio.yml
    #     # kubectl apply -f mongo.yml
    # #     # kubectl create -f external-dns.yml

    - name: Deploy manifest files to EKS
      run: | 
        helm install knote ./knote



        



