name: Deploy AWS Load Balancer Controller
env:
  DOCKER_USER: ${{secrets.DOCKER_HUB_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_TOKEN}}
  DOCKER_REPOSITORY: my-app
  NODE_IMAGE_TAG: knote

on:
  push:
    branches: [ main]

permissions:
  actions: read
  security-events: write
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: 'latest'
    
    - name: Helm init 
      run: helm init --stable-repo-url=https://charts.helm.sh/stable --client-only 
    # - name: Set up eksctl
    #   uses: moia-oss/setup-eksctl@v1
    #   with:
    #     version: 'latest' # default is latest
    #   id: install
        

    # - name: Create IAM OIDC provider
    #   run: |
    #     eksctl utils associate-iam-oidc-provider \
    #     --region <aws-region> \
    #     --cluster prod \
    #     --approve

    # - name: Create IAM OIDC provider
    #   run: |
    #     curl -o iam-policy.json https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/main/docs/install/iam_policy.json

    # - name: Deploy AWS Load Balancer Controller
    #   run: |

    # - name: Create an IAM policy called AWSLoadBalancerControllerIAMPolicy
    #   run: |
    #     aws iam create-policy \
    #     --policy-name AWSLoadBalancerControllerIAMPolicy \
    #     --policy-document file://iam-policy.json

    # - name: Create an IAM policy called AWSLoadBalancerControllerIAMPolicy
    #   run: |
    #     eksctl create iamserviceaccount \
    #     --cluster=prod \
    #     --namespace=kube-system \
    #     --name=aws-load-balancer-controller \
    #     --attach-policy-arn=arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:policy/AWSLoadBalancerControllerIAMPolicy \
    #     --approve

    # - name: Install CRDS
    #   run: |
    #     kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"


    - name: Install load balancer
      run: |
        helm repo update
        helm repo add eks https://aws.github.io/eks-charts
        helm upgrade -i aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system --set clusterName= --set serviceAccount.create=false --set serviceAccount.name=aws-load-balancer-controller

    - name: Install CRDS
      run: |
        kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"
